export interface SongRef {
  title: string;
  artist: string;
}

/** Curated master pool for the default Daily mode — recognizable hits spanning decades/genres. */
export const DAILY_POOL: SongRef[] = [
  { title: "Blinding Lights", artist: "The Weeknd" },
  { title: "Uptown Funk", artist: "Mark Ronson" },
  { title: "Rolling in the Deep", artist: "Adele" },
  { title: "Shape of You", artist: "Ed Sheeran" },
  { title: "Bohemian Rhapsody", artist: "Queen" },
  { title: "Billie Jean", artist: "Michael Jackson" },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses" },
  { title: "Since U Been Gone", artist: "Kelly Clarkson" },
  { title: "Mr. Brightside", artist: "The Killers" },
  { title: "Bad Guy", artist: "Billie Eilish" },
  { title: "Levitating", artist: "Dua Lipa" },
  { title: "Watermelon Sugar", artist: "Harry Styles" },
  { title: "Don't Stop Believin'", artist: "Journey" },
  { title: "Hey Ya!", artist: "OutKast" },
  { title: "Crazy in Love", artist: "Beyonce" },
  { title: "Umbrella", artist: "Rihanna" },
  { title: "Poker Face", artist: "Lady Gaga" },
  { title: "Party in the U.S.A.", artist: "Miley Cyrus" },
  { title: "Rolling Stone", artist: "The Rolling Stones" },
  { title: "Livin' on a Prayer", artist: "Bon Jovi" },
  { title: "Smells Like Teen Spirit", artist: "Nirvana" },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston" },
  { title: "Take On Me", artist: "a-ha" },
  { title: "Africa", artist: "Toto" },
  { title: "Every Breath You Take", artist: "The Police" },
  { title: "Wonderwall", artist: "Oasis" },
  { title: "Get Lucky", artist: "Daft Punk" },
  { title: "Can't Stop the Feeling!", artist: "Justin Timberlake" },
  { title: "Shake It Off", artist: "Taylor Swift" },
  { title: "Someone Like You", artist: "Adele" },
  { title: "Viva la Vida", artist: "Coldplay" },
  { title: "Somebody That I Used to Know", artist: "Gotye" },
  { title: "Uptown Girl", artist: "Billy Joel" },
  { title: "Thriller", artist: "Michael Jackson" },
  { title: "Like a Prayer", artist: "Madonna" },
  { title: "Toxic", artist: "Britney Spears" },
  { title: "Hips Don't Lie", artist: "Shakira" },
  { title: "Firework", artist: "Katy Perry" },
  { title: "Rolling with the Homies", artist: "Beastie Boys" },
  { title: "Sicko Mode", artist: "Travis Scott" },
  { title: "HUMBLE.", artist: "Kendrick Lamar" },
  { title: "God's Plan", artist: "Drake" },
  { title: "Old Town Road", artist: "Lil Nas X" },
  { title: "Sunflower", artist: "Post Malone" },
  { title: "As It Was", artist: "Harry Styles" },
  { title: "Flowers", artist: "Miley Cyrus" },
  { title: "Anti-Hero", artist: "Taylor Swift" },
  { title: "Cruel Summer", artist: "Taylor Swift" },
  { title: "Espresso", artist: "Sabrina Carpenter" },
  { title: "Die With A Smile", artist: "Lady Gaga" },
  { title: "vampire", artist: "Olivia Rodrigo" },
  { title: "Stay", artist: "The Kid LAROI" },
  { title: "Peaches", artist: "Justin Bieber" },
  { title: "drivers license", artist: "Olivia Rodrigo" },
  { title: "good 4 u", artist: "Olivia Rodrigo" },
  { title: "Circles", artist: "Post Malone" },
  { title: "Havana", artist: "Camila Cabello" },
  { title: "Despacito", artist: "Luis Fonsi" },
  { title: "Closer", artist: "The Chainsmokers" },
  { title: "Roar", artist: "Katy Perry" },
  { title: "Counting Stars", artist: "OneRepublic" },
  { title: "Radioactive", artist: "Imagine Dragons" },
  { title: "Rolling in the Deep", artist: "Adele" },
  { title: "No Diggity", artist: "Blackstreet" },
  { title: "I Will Survive", artist: "Gloria Gaynor" },
  { title: "September", artist: "Earth, Wind & Fire" },
  { title: "Dancing Queen", artist: "ABBA" },
  { title: "Superstition", artist: "Stevie Wonder" },
  { title: "Good as Hell", artist: "Lizzo" },
  { title: "Blank Space", artist: "Taylor Swift" },
  { title: "Rolling Stone", artist: "Bob Dylan" },
  { title: "Enter Sandman", artist: "Metallica" },
  { title: "Seven Nation Army", artist: "The White Stripes" },
  { title: "Mr. Blue Sky", artist: "Electric Light Orchestra" },
  { title: "American Idiot", artist: "Green Day" },
  { title: "In the End", artist: "Linkin Park" },
  { title: "Numb", artist: "Linkin Park" },
  { title: "Feel Good Inc.", artist: "Gorillaz" },
  { title: "Clint Eastwood", artist: "Gorillaz" },
  { title: "Boulevard of Broken Dreams", artist: "Green Day" },
  { title: "Mr. Sandman", artist: "The Chordettes" },
  { title: "Stayin' Alive", artist: "Bee Gees" },
  { title: "Kiss From a Rose", artist: "Seal" },
  { title: "Torn", artist: "Natalie Imbruglia" },
];

export const GENRES: { slug: string; label: string; emoji: string; songs: SongRef[] }[] = [
  {
    slug: "pop",
    label: "Pop",
    emoji: "🎤",
    songs: [
      { title: "As It Was", artist: "Harry Styles" },
      { title: "Levitating", artist: "Dua Lipa" },
      { title: "Watermelon Sugar", artist: "Harry Styles" },
      { title: "Anti-Hero", artist: "Taylor Swift" },
      { title: "Cruel Summer", artist: "Taylor Swift" },
      { title: "Espresso", artist: "Sabrina Carpenter" },
      { title: "Die With A Smile", artist: "Lady Gaga" },
      { title: "vampire", artist: "Olivia Rodrigo" },
      { title: "drivers license", artist: "Olivia Rodrigo" },
      { title: "Firework", artist: "Katy Perry" },
      { title: "Roar", artist: "Katy Perry" },
      { title: "Bad Guy", artist: "Billie Eilish" },
      { title: "Shape of You", artist: "Ed Sheeran" },
      { title: "Blinding Lights", artist: "The Weeknd" },
      { title: "Toxic", artist: "Britney Spears" },
      { title: "Poker Face", artist: "Lady Gaga" },
      { title: "Since U Been Gone", artist: "Kelly Clarkson" },
      { title: "Party in the U.S.A.", artist: "Miley Cyrus" },
      { title: "Flowers", artist: "Miley Cyrus" },
      { title: "Wrecking Ball", artist: "Miley Cyrus" },
      { title: "Shake It Off", artist: "Taylor Swift" },
      { title: "Blank Space", artist: "Taylor Swift" },
      { title: "Rolling in the Deep", artist: "Adele" },
      { title: "Someone Like You", artist: "Adele" },
      { title: "Good 4 U", artist: "Olivia Rodrigo" },
      { title: "Stay", artist: "The Kid LAROI" },
      { title: "Peaches", artist: "Justin Bieber" },
      { title: "Sorry", artist: "Justin Bieber" },
      { title: "Havana", artist: "Camila Cabello" },
      { title: "Señorita", artist: "Shawn Mendes" },
    ],
  },
  {
    slug: "hiphop",
    label: "Hip-Hop / Rap",
    emoji: "🎧",
    songs: [
      { title: "Sicko Mode", artist: "Travis Scott" },
      { title: "HUMBLE.", artist: "Kendrick Lamar" },
      { title: "God's Plan", artist: "Drake" },
      { title: "Old Town Road", artist: "Lil Nas X" },
      { title: "Sunflower", artist: "Post Malone" },
      { title: "Circles", artist: "Post Malone" },
      { title: "In Da Club", artist: "50 Cent" },
      { title: "Lose Yourself", artist: "Eminem" },
      { title: "Sicko Mode", artist: "Travis Scott" },
      { title: "Hotline Bling", artist: "Drake" },
      { title: "One Dance", artist: "Drake" },
      { title: "Gods Plan", artist: "Drake" },
      { title: "Alright", artist: "Kendrick Lamar" },
      { title: "DNA.", artist: "Kendrick Lamar" },
      { title: "Not Like Us", artist: "Kendrick Lamar" },
      { title: "Money Trees", artist: "Kendrick Lamar" },
      { title: "Rap God", artist: "Eminem" },
      { title: "Stan", artist: "Eminem" },
      { title: "Empire State of Mind", artist: "JAY-Z" },
      { title: "Ni**as in Paris", artist: "JAY-Z" },
      { title: "Hey Ya!", artist: "OutKast" },
      { title: "No Diggity", artist: "Blackstreet" },
      { title: "Gold Digger", artist: "Kanye West" },
      { title: "Stronger", artist: "Kanye West" },
      { title: "Heartless", artist: "Kanye West" },
      { title: "goosebumps", artist: "Travis Scott" },
      { title: "THE LONDON", artist: "Young Thug" },
      { title: "Life Is Good", artist: "Future" },
      { title: "Bodak Yellow", artist: "Cardi B" },
      { title: "WAP", artist: "Cardi B" },
    ],
  },
  {
    slug: "rock",
    label: "Rock",
    emoji: "🎸",
    songs: [
      { title: "Bohemian Rhapsody", artist: "Queen" },
      { title: "Sweet Child O' Mine", artist: "Guns N' Roses" },
      { title: "Mr. Brightside", artist: "The Killers" },
      { title: "Smells Like Teen Spirit", artist: "Nirvana" },
      { title: "Livin' on a Prayer", artist: "Bon Jovi" },
      { title: "Don't Stop Believin'", artist: "Journey" },
      { title: "Enter Sandman", artist: "Metallica" },
      { title: "Seven Nation Army", artist: "The White Stripes" },
      { title: "American Idiot", artist: "Green Day" },
      { title: "Boulevard of Broken Dreams", artist: "Green Day" },
      { title: "In the End", artist: "Linkin Park" },
      { title: "Numb", artist: "Linkin Park" },
      { title: "Wonderwall", artist: "Oasis" },
      { title: "Come As You Are", artist: "Nirvana" },
      { title: "Under the Bridge", artist: "Red Hot Chili Peppers" },
      { title: "Californication", artist: "Red Hot Chili Peppers" },
      { title: "Africa", artist: "Toto" },
      { title: "Every Breath You Take", artist: "The Police" },
      { title: "Highway to Hell", artist: "AC/DC" },
      { title: "Back in Black", artist: "AC/DC" },
      { title: "Free Bird", artist: "Lynyrd Skynyrd" },
      { title: "Hotel California", artist: "Eagles" },
      { title: "Stairway to Heaven", artist: "Led Zeppelin" },
      { title: "Should I Stay or Should I Go", artist: "The Clash" },
      { title: "Basket Case", artist: "Green Day" },
      { title: "Radioactive", artist: "Imagine Dragons" },
      { title: "Believer", artist: "Imagine Dragons" },
      { title: "Thunderstruck", artist: "AC/DC" },
      { title: "Creep", artist: "Radiohead" },
      { title: "Learn to Fly", artist: "Foo Fighters" },
    ],
  },
  {
    slug: "rnb",
    label: "R&B / Soul",
    emoji: "💜",
    songs: [
      { title: "Crazy in Love", artist: "Beyonce" },
      { title: "Umbrella", artist: "Rihanna" },
      { title: "I Wanna Dance with Somebody", artist: "Whitney Houston" },
      { title: "No Diggity", artist: "Blackstreet" },
      { title: "September", artist: "Earth, Wind & Fire" },
      { title: "Superstition", artist: "Stevie Wonder" },
      { title: "Halo", artist: "Beyonce" },
      { title: "Single Ladies (Put a Ring on It)", artist: "Beyonce" },
      { title: "Location", artist: "Khalid" },
      { title: "Best Part", artist: "Daniel Caesar" },
      { title: "Adorn", artist: "Miguel" },
      { title: "Blinding Lights", artist: "The Weeknd" },
      { title: "Earned It", artist: "The Weeknd" },
      { title: "Die For You", artist: "The Weeknd" },
      { title: "Say My Name", artist: "Destiny's Child" },
      { title: "No Scrubs", artist: "TLC" },
      { title: "Waterfalls", artist: "TLC" },
      { title: "I Believe I Can Fly", artist: "R. Kelly" },
      { title: "Ain't No Sunshine", artist: "Bill Withers" },
      { title: "Lean On Me", artist: "Bill Withers" },
      { title: "Respect", artist: "Aretha Franklin" },
      { title: "What's Going On", artist: "Marvin Gaye" },
      { title: "Let's Get It On", artist: "Marvin Gaye" },
      { title: "Rock With You", artist: "Michael Jackson" },
      { title: "Billie Jean", artist: "Michael Jackson" },
      { title: "Adore You", artist: "Miguel" },
      { title: "Pillowtalk", artist: "Zayn" },
      { title: "Cranes in the Sky", artist: "Solange" },
      { title: "Redbone", artist: "Childish Gambino" },
      { title: "Come Through and Chill", artist: "Miguel" },
    ],
  },
  {
    slug: "country",
    label: "Country",
    emoji: "🤠",
    songs: [
      { title: "Cruise", artist: "Florida Georgia Line" },
      { title: "Body Like a Back Road", artist: "Sam Hunt" },
      { title: "Wagon Wheel", artist: "Darius Rucker" },
      { title: "Chicken Fried", artist: "Zac Brown Band" },
      { title: "Before He Cheats", artist: "Carrie Underwood" },
      { title: "Need You Now", artist: "Lady A" },
      { title: "Follow Your Arrow", artist: "Kacey Musgraves" },
      { title: "Tennessee Whiskey", artist: "Chris Stapleton" },
      { title: "Jolene", artist: "Dolly Parton" },
      { title: "Ring of Fire", artist: "Johnny Cash" },
      { title: "Take Me Home, Country Roads", artist: "John Denver" },
      { title: "Friends in Low Places", artist: "Garth Brooks" },
      { title: "The Dance", artist: "Garth Brooks" },
      { title: "Fancy Like", artist: "Walker Hayes" },
      { title: "Old Town Road", artist: "Lil Nas X" },
      { title: "Blue Ain't Your Color", artist: "Keith Urban" },
      { title: "Dirt Road Anthem", artist: "Jason Aldean" },
      { title: "Girl Crush", artist: "Little Big Town" },
      { title: "Speed", artist: "Chris Stapleton" },
      { title: "The Bones", artist: "Maren Morris" },
      { title: "Fast Car", artist: "Luke Combs" },
      { title: "Save It for a Rainy Day", artist: "Kenny Chesney" },
      { title: "Copperhead Road", artist: "Steve Earle" },
      { title: "Austin", artist: "Blake Shelton" },
      { title: "Humble and Kind", artist: "Tim McGraw" },
      { title: "Live Like You Were Dying", artist: "Tim McGraw" },
      { title: "Cowboy Like Me", artist: "Taylor Swift" },
      { title: "Suds in the Bucket", artist: "Sara Evans" },
      { title: "Strawberry Wine", artist: "Deana Carter" },
      { title: "Achy Breaky Heart", artist: "Billy Ray Cyrus" },
    ],
  },
  {
    slug: "dance",
    label: "Dance / Electronic",
    emoji: "🪩",
    songs: [
      { title: "Get Lucky", artist: "Daft Punk" },
      { title: "One More Time", artist: "Daft Punk" },
      { title: "Levels", artist: "Avicii" },
      { title: "Wake Me Up", artist: "Avicii" },
      { title: "Titanium", artist: "David Guetta" },
      { title: "Animals", artist: "Martin Garrix" },
      { title: "Clarity", artist: "Zedd" },
      { title: "Don't You Worry Child", artist: "Swedish House Mafia" },
      { title: "Closer", artist: "The Chainsmokers" },
      { title: "Roses", artist: "The Chainsmokers" },
      { title: "Lean On", artist: "Major Lazer" },
      { title: "Faded", artist: "Alan Walker" },
      { title: "This Is What You Came For", artist: "Calvin Harris" },
      { title: "Summer", artist: "Calvin Harris" },
      { title: "Feel So Close", artist: "Calvin Harris" },
      { title: "Sandstorm", artist: "Darude" },
      { title: "Around the World", artist: "Daft Punk" },
      { title: "Strobe", artist: "Deadmau5" },
      { title: "Ghosts 'n' Stuff", artist: "Deadmau5" },
      { title: "Levitating", artist: "Dua Lipa" },
      { title: "Don't Start Now", artist: "Dua Lipa" },
      { title: "One Kiss", artist: "Calvin Harris" },
      { title: "In My Mind", artist: "Dynoro" },
      { title: "Selfish Love", artist: "Sean Paul" },
      { title: "I Gotta Feeling", artist: "The Black Eyed Peas" },
      { title: "Blame", artist: "Calvin Harris" },
      { title: "Where Are Ü Now", artist: "Jack Ü" },
      { title: "Silhouettes", artist: "Avicii" },
      { title: "Turn Down for What", artist: "DJ Snake" },
      { title: "Lush Life", artist: "Zara Larsson" },
    ],
  },
  {
    slug: "kpop",
    label: "K-Pop",
    emoji: "🇰🇷",
    songs: [
      { title: "Dynamite", artist: "BTS" },
      { title: "Butter", artist: "BTS" },
      { title: "Boy With Luv", artist: "BTS" },
      { title: "DNA", artist: "BTS" },
      { title: "Fake Love", artist: "BTS" },
      { title: "How You Like That", artist: "BLACKPINK" },
      { title: "Kill This Love", artist: "BLACKPINK" },
      { title: "Pink Venom", artist: "BLACKPINK" },
      { title: "DDU-DU DDU-DU", artist: "BLACKPINK" },
      { title: "Gangnam Style", artist: "PSY" },
      { title: "Cupid", artist: "FIFTY FIFTY" },
      { title: "Next Level", artist: "aespa" },
      { title: "Spicy", artist: "aespa" },
      { title: "LOVE DIVE", artist: "IVE" },
      { title: "Attention", artist: "NewJeans" },
      { title: "Super Shy", artist: "NewJeans" },
      { title: "OMG", artist: "NewJeans" },
      { title: "Ditto", artist: "NewJeans" },
      { title: "Antifragile", artist: "LE SSERAFIM" },
      { title: "UNFORGIVEN", artist: "LE SSERAFIM" },
      { title: "God's Menu", artist: "Stray Kids" },
      { title: "S-Class", artist: "Stray Kids" },
      { title: "MANIAC", artist: "Stray Kids" },
      { title: "Fancy", artist: "TWICE" },
      { title: "Feel Special", artist: "TWICE" },
      { title: "TT", artist: "TWICE" },
      { title: "Psycho", artist: "Red Velvet" },
      { title: "Bad Boy", artist: "Red Velvet" },
      { title: "Growl", artist: "EXO" },
      { title: "Love Shot", artist: "EXO" },
    ],
  },
  {
    slug: "latin",
    label: "Latin",
    emoji: "🔥",
    songs: [
      { title: "Despacito", artist: "Luis Fonsi" },
      { title: "Hips Don't Lie", artist: "Shakira" },
      { title: "Bailando", artist: "Enrique Iglesias" },
      { title: "Gasolina", artist: "Daddy Yankee" },
      { title: "Con Calma", artist: "Daddy Yankee" },
      { title: "Mi Gente", artist: "J Balvin" },
      { title: "Ginza", artist: "J Balvin" },
      { title: "I Like It", artist: "Cardi B" },
      { title: "China", artist: "Anuel AA" },
      { title: "Tusa", artist: "Karol G" },
      { title: "Provenza", artist: "Karol G" },
      { title: "Felices los 4", artist: "Maluma" },
      { title: "Chantaje", artist: "Shakira" },
      { title: "Waka Waka", artist: "Shakira" },
      { title: "La Bicicleta", artist: "Carlos Vives" },
      { title: "Danza Kuduro", artist: "Don Omar" },
      { title: "Vivir Mi Vida", artist: "Marc Anthony" },
      { title: "Bailar", artist: "Deorro" },
      { title: "Baila Esta Cumbia", artist: "Selena" },
      { title: "Como La Flor", artist: "Selena" },
      { title: "La Bamba", artist: "Ritchie Valens" },
      { title: "Suavemente", artist: "Elvis Crespo" },
      { title: "Livin' la Vida Loca", artist: "Ricky Martin" },
      { title: "MAMIII", artist: "Karol G" },
      { title: "TQG", artist: "Karol G" },
      { title: "Ella Baila Sola", artist: "Eslabon Armado" },
      { title: "Un x100to", artist: "Grupo Frontera" },
      { title: "Me Porto Bonito", artist: "Bad Bunny" },
      { title: "Titi Me Preguntó", artist: "Bad Bunny" },
      { title: "DÁKITI", artist: "Bad Bunny" },
    ],
  },
  {
    slug: "indie",
    label: "Indie / Alternative",
    emoji: "🌙",
    songs: [
      { title: "Somebody That I Used to Know", artist: "Gotye" },
      { title: "Mr. Brightside", artist: "The Killers" },
      { title: "Take Me Out", artist: "Franz Ferdinand" },
      { title: "Feel Good Inc.", artist: "Gorillaz" },
      { title: "Clint Eastwood", artist: "Gorillaz" },
      { title: "1901", artist: "Phoenix" },
      { title: "Lisztomania", artist: "Phoenix" },
      { title: "Reptilia", artist: "The Strokes" },
      { title: "Last Nite", artist: "The Strokes" },
      { title: "Skinny Love", artist: "Bon Iver" },
      { title: "Holocene", artist: "Bon Iver" },
      { title: "Electric Feel", artist: "MGMT" },
      { title: "Kids", artist: "MGMT" },
      { title: "Two Weeks", artist: "FKA twigs" },
      { title: "Pumped Up Kicks", artist: "Foster the People" },
      { title: "Little Talks", artist: "Of Monsters and Men" },
      { title: "Ho Hey", artist: "The Lumineers" },
      { title: "Home", artist: "Edward Sharpe & The Magnetic Zeros" },
      { title: "Riptide", artist: "Vance Joy" },
      { title: "Youth", artist: "Daughter" },
      { title: "Dog Days Are Over", artist: "Florence + the Machine" },
      { title: "Shake It Out", artist: "Florence + the Machine" },
      { title: "1234", artist: "Feist" },
      { title: "Time to Dance", artist: "The Sounds" },
      { title: "Do I Wanna Know?", artist: "Arctic Monkeys" },
      { title: "R U Mine?", artist: "Arctic Monkeys" },
      { title: "505", artist: "Arctic Monkeys" },
      { title: "Somewhere Only We Know", artist: "Keane" },
      { title: "The Less I Know the Better", artist: "Tame Impala" },
      { title: "Let It Happen", artist: "Tame Impala" },
    ],
  },
];
